### ISSUE TITLE
struct.error: 1 bytes required

### ISSUE THREAD

**Issue by DinacoStudio** [fnmwolf/Anaconda#11]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Anaconda\x64\tools\bimbam.py", line 83, in <module>
    main()
  File "C:\Users\User\Desktop\Anaconda\x64\tools\bimbam.py", line 48, in main
    newExe = ExecutableData(fp, loadImages=True)
  File "mmfparser\loader.pyx", line 20, in mmfparser.loader.DataLoader.__init__ (./mmfparser/loader.cpp:936)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1051)
  File "mmfparser\loader.pyx", line 49, in mmfparser.loader.DataLoader.read (./mmfparser/loader.cpp:1714)
  File "..\mmfparser\data\exe.py", line 34, in read
    firstShort = reader.readShort()
  File "mmfparser\bytereader.pyx", line 259, in mmfparser.bytereader.ByteReader.readShort (./mmfparser/bytereader.cpp:3823)
  File "mmfparser\bytereader.pyx", line 262, in mmfparser.bytereader.ByteReader.readShort (./mmfparser/bytereader.cpp:3682)
  File "mmfparser\bytereader.pyx", line 178, in mmfparser.bytereader.ByteReader._read (./mmfparser/bytereader.cpp:2720)

**Comment by fnmwolf** [comment]
Most likely, the game is 2.5+ and therefore not supported by anaconda.  Send me the game exe and I’ll check it out.

**Comment by v-atamanenko** [comment]
@fnmwolf Hi. I have the same problem with Baba is you. If you want me to share the exe or anything else, please contact me at `gl33ntwine#7290` on Discord.

**Comment by 055110** [comment]
it is a 2.5+

**Comment by fnmwolf** [comment]
@CoolestGuy94 alright send me the exe ill decompile it with my private tool

@v-atamanenko any luck with your LUA project we discussed in discord?

**Comment by 055110** [comment]
https://anonfiles.com/r3FfL1X3x5/mini-boshy-with-love-1.95_exe

**Comment by fnmwolf** [comment]
@CoolestGuy94 I've attempted to decompile your game with the beta 2.5+ decompiler: here is the result
https://ufile.io/ezply59t

**Comment by jakobhellermann** [comment]
I get the same error trying to decompile https://store.steampowered.com/app/1674780/Lone_Fungus/. Is the beta 2.5+ decompiler publicly available somewhere @fnmwolf? This is the exe btw https://anonfiles.com/n4h4Jcr3y3/Lone_Fungus_exe.
