### ISSUE TITLE
anothere error

### ISSUE THREAD

**Issue by engineergamingistaking** [fnmwolf/Anaconda#8]
when trying to decompile i get this error: ImportError: DLL load failed: %1 is not a valid Win32 application.

someone help

**Comment by fnmwolf** [comment]
You need to use the 64-bit version of Python 2.7.18 - the installer is included with your Anaconda download.

**Comment by engineergamingistaking** [comment]
ok, installed the 64-bit version of python 2.7.18, but now its sending me this:

(unknown chunk 8774)
(unknown chunk 8785)
creating new data transform
(unknown chunk 8783)
(unknown chunk 8794)
(unknown chunk 8793)
(unknown chunk 8792)
(unknown chunk 8787)
(unknown chunk 8788)
(unknown chunk 8789)
(unknown chunk 8790)
(unknown chunk 8791)
(unknown chunk 8781)
  File "bimbam.py", line 83, in <module>
    main()
  File "bimbam.py", line 48, in main
    newExe = ExecutableData(fp, loadImages=True)
  File "..\mmfparser\data\exe.py", line 55, in read
    self.gameData = self.new(GameData, reader)
  File "..\mmfparser\data\gamedata.py", line 102, in read
    chunks = self.new(ChunkList, reader)
Traceback (most recent call last):
  File "bimbam.py", line 83, in <module>
    main()
  File "bimbam.py", line 48, in main
    newExe = ExecutableData(fp, loadImages=True)
  File "mmfparser\loader.pyx", line 20, in mmfparser.loader.DataLoader.__init__ (./mmfparser/loader.cpp:936)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1051)
  File "mmfparser\loader.pyx", line 49, in mmfparser.loader.DataLoader.read (./mmfparser/loader.cpp:1714)
  File "..\mmfparser\data\exe.py", line 55, in read
    self.gameData = self.new(GameData, reader)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1245)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1051)
  File "mmfparser\loader.pyx", line 49, in mmfparser.loader.DataLoader.read (./mmfparser/loader.cpp:1714)
  File "..\mmfparser\data\gamedata.py", line 102, in read
    chunks = self.new(ChunkList, reader)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1245)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1051)
  File "mmfparser\data\chunk.pyx", line 172, in mmfparser.data.chunk.ChunkList.read (./mmfparser/data/chunk.cpp:4275)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1245)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1051)
  File "mmfparser\data\chunk.pyx", line 86, in mmfparser.data.chunk.Chunk.read (./mmfparser/data/chunk.cpp:2371)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1245)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1051)
  File "mmfparser\data\chunkloaders\imagebank.pyx", line 574, in mmfparser.data.chunkloaders.imagebank.ImageBank.read (./mmfparser/data/chunkloaders/imagebank.cpp:11580)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1245)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1051)
  File "mmfparser\data\chunkloaders\imagebank.pyx", line 367, in mmfparser.data.chunkloaders.imagebank.ImageItem.read (./mmfparser/data/chunkloaders/imagebank.cpp:4875)
  File "mmfparser\bytereader.pyx", line 282, in mmfparser.bytereader.ByteReader.readInt (./mmfparser/bytereader.cpp:4070)
  File "mmfparser\bytereader.pyx", line 190, in mmfparser.bytereader.ByteReader._read (./mmfparser/bytereader.cpp:2761)
  File "mmfparser\bytereader.pyx", line 50, in mmfparser.bytereader.check_available (./mmfparser/bytereader.cpp:1186)
struct.error: 1 bytes required

**Comment by fnmwolf** [comment]
This is because the game is a 2.5+ game which is not supported, if you want send me the download link to the game and I will decompile it for you with a private 2.5+ tool
